AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ShrinkIt  
  Sample SAM Template for ShrinkIt

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ShrinkIt
    Description: ShrinkIt is a lightweight, serverless application that lets you create
      and manage shortened URLs easily.
    Author: Ticat Wolves
    SpdxLicenseId: MIT
    LicenseUrl: s3://shrinkit-prod/LICENSE
    ReadmeUrl: s3://shrinkit-prod/README.md
    Labels:
    - URL
    - shortening
    HomePageUrl: https://github.com/ticatwolves/shrinkIt
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/ticatwolves/shrinkIt

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "GET,POST,OPTIONS"
      AllowHeaders: "content-type"
      AllowOrigin: "'*'" # add your origin here

Resources:
  ShrinkItApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        GetPath:
            Type: HttpApi
            Properties:
              Path: /
              Method: GET
        PostPath:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE: ShrinkItUrlMapping
          DYNAMODB_ENDPOINT: ""
          API_ENDPOINT: "https://YOUR_HOSTED_URL"
      Policies:
        - Statement: # Example of an inline policy
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt ShrinkItDB.Arn
  ShrinkItDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: urlHash
        Type: String
      TableName: ShrinkItUrlMapping
      Tags:
        PROJECT: ShrinkIt

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShrinkItApiFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ShrinkItApiFunction.Arn
  ShrinkItApiFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt ShrinkItApiFunctionRole.Arn
